name: Build and Deploy to GHCR.io

on: workflow_dispatch

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-non-latest-images:
    name: "Build and Push non-latest Image"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [fermium-alpine, fermium-slim, fermium, gallium-alpine, gallium-slim, gallium, hydrogen-slim, hydrogen]
    permissions:
      contents: read
      packages: write
    
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v3
      -
        name: Login to Docker Registries
        uses: ./.github/actions/docker-registry-setup
        with:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          GHCR_USERNAME: ${{ github.actor }}
          GHCR_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args: NODE_VERSION=${{ matrix.node_version }}
          push: true
          tags: andreasfahrecker/node-pnpm:${{ matrix.node_version }},ghcr.io/andreas-fahrecker/node-pnpm:${{ matrix.node_version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-and-push-latest-image:
    name: "Build and Push Latest Image"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v3
      -
        name: Login to Docker Registries
        uses: ./.github/actions/docker-registry-setup
        with:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          GHCR_USERNAME: ${{ github.actor }}
          GHCR_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push Docker image hydrogen-alpine
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args: NODE_VERSION=hydrogen-alpine
          push: true
          tags: andreasfahrecker/node-pnpm:latest,andreasfahrecker/node-pnpm:hydrogen-alpine,ghcr.io/andreas-fahrecker/node-pnpm:latest,ghcr.io/andreas-fahrecker/node-pnpm:hydrogen-alpine
          cache-from: type=gha
          cache-to: type=gha,mode=max
