name: Build and Deploy to GHCR.io

on: workflow_dispatch

env:
  REGISTRY: ghcr.io

jobs:
  setup:
    name: "Checkout and Login to Docker Registries"
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

  build-and-push-fermium-image:
    name: "Build and Push Fermium"
    runs-on: ubuntu-latest
    needs: setup
    permissions:
      contents: read
      packages: write
    
    steps:
      -
        name: Build and push Docker image fermium-alpine
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args: NODE_VERSION=fermium-alpine
          push: true
          tags: andreasfahrecker/node-pnpm:fermium-alpine,ghcr.io/andreas-fahrecker/node-pnpm:fermium-alpine
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-and-push-gallium-image:
    name: "Build and Push Gallium"
    runs-on: ubuntu-latest
    needs: setup
    permissions:
      contents: read
      packages: write
    
    steps:
      -
        name: Build and push Docker image gallium-alpine
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args: NODE_VERSION=gallium-alpine
          push: true
          tags: andreasfahrecker/node-pnpm:gallium-alpine,ghcr.io/andreas-fahrecker/node-pnpm:gallium-alpine
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-and-push-hydrogen-image:
    name: "Build and Push Hydrogen"
    runs-on: ubuntu-latest
    needs: setup
    permissions:
      contents: read
      packages: write
    
    steps:
      -
        name: Build and push Docker image hydrogen-alpine
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args: NODE_VERSION=hydrogen-alpine
          push: true
          tags: andreasfahrecker/node-pnpm:latest,andreasfahrecker/node-pnpm:hydrogen-alpine,ghcr.io/andreas-fahrecker/node-pnpm:latest,ghcr.io/andreas-fahrecker/node-pnpm:hydrogen-alpine
          cache-from: type=gha
          cache-to: type=gha,mode=max
