name: Build and Deploy to GHCR.io

on: workflow_dispatch

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-fermium-image:
    name: "Build and Push Fermium"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      -
        name: Setup
        uses: ./.github/actions/setup
      -
        name: Build and push Docker image fermium-alpine
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args: NODE_VERSION=fermium-alpine
          push: true
          tags: andreasfahrecker/node-pnpm:fermium-alpine,ghcr.io/andreas-fahrecker/node-pnpm:fermium-alpine
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-and-push-gallium-image:
    name: "Build and Push Gallium"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      -
        name: Setup
        uses: ./.github/actions/setup
      -
        name: Build and push Docker image gallium-alpine
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args: NODE_VERSION=gallium-alpine
          push: true
          tags: andreasfahrecker/node-pnpm:gallium-alpine,ghcr.io/andreas-fahrecker/node-pnpm:gallium-alpine
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-and-push-hydrogen-image:
    name: "Build and Push Hydrogen"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      -
        name: Setup
        uses: ./.github/actions/setup
      -
        name: Build and push Docker image hydrogen-alpine
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args: NODE_VERSION=hydrogen-alpine
          push: true
          tags: andreasfahrecker/node-pnpm:latest,andreasfahrecker/node-pnpm:hydrogen-alpine,ghcr.io/andreas-fahrecker/node-pnpm:latest,ghcr.io/andreas-fahrecker/node-pnpm:hydrogen-alpine
          cache-from: type=gha
          cache-to: type=gha,mode=max
