name: Build and Deploy to GHCR.io

on: workflow_dispatch

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image fermium-alpine
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args: NODE_VERSION=fermium-alpine
          push: true
          tags: ghcr.io/andreas-fahrecker/nodepnpm:fermium-alpine
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Docker image gallium-alpine
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args: NODE_VERSION=gallium-alpine
          push: true
          tags: ghcr.io/andreas-fahrecker/nodepnpm:gallium-alpine
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Docker image hydrogen-alpine
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args: NODE_VERSION=hydrogen-alpine
          push: true
          tags: ghcr.io/andreas-fahrecker/nodepnpm:latest,ghcr.io/andreas-fahrecker/nodepnpm:hydrogen-alpine
          cache-from: type=gha
          cache-to: type=gha,mode=max
